source ~/.zshrc.omz
source ~/.zshrc.git

# aliases
alias ..='cd ..'
alias tig='tig status'
alias l='ls -lah'

# vi mode
bindkey -v

# search history
bindkey '^r' history-incremental-search-backward

# local overrides
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
